apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: agafumiya/laravel-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: production
